-- MySQL Script generated by MySQL Workbench
-- Fri Sep 29 10:24:49 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`agendamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`agendamento` (
  `cod_age` INT NOT NULL AUTO_INCREMENT,
  `data_age` DATE NULL,
  `hora_age` TIME NULL,
  `unidade` BIGINT(20) NULL,
  `cliente` BIGINT(20) NULL,
  `corte_cabelo` BIGINT(20) NULL,
  `corte_barba` BIGINT(20) NULL,
  `valor_total` FLOAT(20) NULL,
  PRIMARY KEY (`cod_age`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`USUARIO` (
  `cod_usr` INT NOT NULL AUTO_INCREMENT,
  `nome_usr` VARCHAR(50) NULL,
  `tel_usr` VARCHAR(20) NULL,
  `email_usr` VARCHAR(20) NULL,
  `senha_usr` VARCHAR(50) NULL,
  `tipo_usr` VARCHAR(50) NULL,
  `rua_usr` VARCHAR(300) NULL,
  `bairro_usr` VARCHAR(50) NULL,
  `cep_usr` VARCHAR(50) NULL,
  `cidade_usr` VARCHAR(50) NULL,
  `estado_usr` VARCHAR(20) NULL,
  `agendamento_cod_age` INT NOT NULL,
  PRIMARY KEY (`cod_usr`, `agendamento_cod_age`),
  INDEX `fk_USUARIO_agendamento_idx` (`agendamento_cod_age` ASC),
  CONSTRAINT `fk_USUARIO_agendamento`
    FOREIGN KEY (`agendamento_cod_age`)
    REFERENCES `mydb`.`agendamento` (`cod_age`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`cortes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cortes` (
  `cod_corte` INT NOT NULL AUTO_INCREMENT,
  `desc_corte` VARCHAR(500) NULL,
  `tipo_corte` VARCHAR(20) NULL,
  `foto_corte` BLOB(500) NULL,
  `valor_cabelo` FLOAT(20) NULL,
  `agendamento_cod_age` INT NOT NULL,
  PRIMARY KEY (`cod_corte`, `agendamento_cod_age`),
  INDEX `fk_cortes_agendamento1_idx` (`agendamento_cod_age` ASC),
  CONSTRAINT `fk_cortes_agendamento1`
    FOREIGN KEY (`agendamento_cod_age`)
    REFERENCES `mydb`.`agendamento` (`cod_age`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`unidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`unidade` (
  `cod_unidade` INT NOT NULL AUTO_INCREMENT,
  `tel_nidade` VARCHAR(20) NULL,
  `rua_unidade` VARCHAR(300) NULL,
  `bairro_unidade` VARCHAR(50) NULL,
  `cep_unidade` VARCHAR(45) NULL,
  `cidade_unidade` VARCHAR(50) NULL,
  `estado_unidade` VARCHAR(50) NULL,
  `unidadecol` VARCHAR(45) NULL,
  `agendamento_cod_age` INT NOT NULL,
  PRIMARY KEY (`cod_unidade`, `agendamento_cod_age`),
  INDEX `fk_unidade_agendamento1_idx` (`agendamento_cod_age` ASC),
  CONSTRAINT `fk_unidade_agendamento1`
    FOREIGN KEY (`agendamento_cod_age`)
    REFERENCES `mydb`.`agendamento` (`cod_age`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
