# Generated by Django 2.2.1 on 2019-05-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CPF_CNPJ_CLI', models.CharField(max_length=14)),
                ('STA_CLI', models.CharField(max_length=1)),
                ('EML_CLI', models.CharField(max_length=150)),
                ('NOME_CLI', models.CharField(max_length=300)),
            ],
        ),
    ]
