# Generated by Django 2.2.1 on 2019-05-06 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pessoa',
            new_name='Cliente',
        ),
    ]
